# 📊 AI & Data Science Job Market Analysis — 2020 to 2024
### Tools Used: Python · Pandas · Tableau Public
### Dataset: AI/ML/Data Science Job Salaries | Source: Kaggle

##  Business Problem

The AI and Data Science job market is growing rapidly. Professionals and
organizations lack clear visibility into:
- Which roles pay the highest salaries globally?
- How does experience level impact compensation?
- Which countries are top hiring hubs for AI talent?
- Is remote work becoming the norm in Data Science?
- How has the market grown from 2020 to 2024?

##  Goal

To perform end-to-end data analysis on global AI & Data Science job
salaries and build an interactive Tableau dashboard that helps:
- Job seekers understand best-paying roles and locations
- Recruiters benchmark salaries across experience levels
- Organizations understand global AI hiring and remote work trends

## 📌 Key Questions This Analysis Answers
1. Which job titles command the highest average salary?
2. How much does experience level impact pay?
3. Which countries hire the most AI/ML professionals?
4. What is the split between Remote, Hybrid, and On-Site roles?
5. How has AI job market volume grown year over year?

## ✅ Expected Outcome

Interactive Tableau dashboard with 6 visualizations + filters

### Step 1 — Import Libraries & Load Dataset

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
import warnings
warnings.filterwarnings('ignore')

In [3]:
dataset = pd.read_csv(r"C:\Users\Shravani\Downloads\ds_salaries.csv")
dataset

,work_year,experience_level,employment_type,job_title,salary,salary_currency,salary_in_usd,employee_residence,remote_ratio,company_location,company_size
0,2023,SE,FT,Principal Data Scientist,80000,EUR,85847,ES,100,ES,L
1,2023,MI,CT,ML Engineer,30000,USD,30000,US,100,US,S
2,2023,MI,CT,ML Engineer,25500,USD,25500,US,100,US,S
3,2023,SE,FT,Data Scientist,175000,USD,175000,CA,100,CA,M
4,2023,SE,FT,Data Scientist,120000,USD,120000,CA,100,CA,M
...,...,...,...,...,...,...,...,...,...,...,...
3750,2020,SE,FT,Data Scientist,412000,USD,412000,US,100,US,L
3751,2021,MI,FT,Principal Data Scientist,151000,USD,151000,US,100,US,L
3752,2020,EN,FT,Data Scientist,105000,USD,105000,US,100,US,S
3753,2020,EN,CT,Business Data Analyst,100000,USD,100000,US,100,US,L
3754,2021,SE,FT,Data Science Manager,7000000,INR,94665,IN,50,IN,L

 ### Step 2 — Data Inspection

In [4]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3755 entries, 0 to 3754
Data columns (total 11 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   work_year           3755 non-null   int64
 1   experience_level    3755 non-null   object
 2   employment_type     3755 non-null   object
 3   job_title           3755 non-null   object
 4   salary              3755 non-null   int64
 5   salary_currency     3755 non-null   object
 6   salary_in_usd       3755 non-null   int64
 7   employee_residence  3755 non-null   object
 8   remote_ratio        3755 non-null   int64
 9   company_location    3755 non-null   object
 10  company_size        3755 non-null   object
dtypes: int64(4), object(7)
memory usage: 322.8+ KB

In [5]:
dataset.shape

(3755, 11)

In [6]:
dataset.isnull().sum()

work_year             0
experience_level      0
employment_type       0
job_title             0
salary                0
salary_currency       0
salary_in_usd         0
employee_residence    0
remote_ratio          0
company_location      0
company_size          0
dtype: int64

In [7]:
dataset['salary_in_usd'].describe()

count      3755.000000
mean     137570.389880
std       63055.625278
min        5132.000000
25%       95000.000000
50%      135000.000000
75%      175000.000000
max      450000.000000
Name: salary_in_usd, dtype: float64

In [8]:
print(f'Total unique jobs: {dataset["job_title"].nunique()}')

Total unique jobs: 93

### Step 3 — Data Cleaning & Transformation

### Replace experience level codes

In [9]:

dataset['experience_level'] = dataset['experience_level'].replace({
    'EN': 'Entry Level',
    'MI': 'Mid Level',
    'SE': 'Senior Level',
    'EX': 'Executive'
})

In [10]:
dataset

,work_year,experience_level,employment_type,job_title,salary,salary_currency,salary_in_usd,employee_residence,remote_ratio,company_location,company_size
0,2023,Senior Level,FT,Principal Data Scientist,80000,EUR,85847,ES,100,ES,L
1,2023,Mid Level,CT,ML Engineer,30000,USD,30000,US,100,US,S
2,2023,Mid Level,CT,ML Engineer,25500,USD,25500,US,100,US,S
3,2023,Senior Level,FT,Data Scientist,175000,USD,175000,CA,100,CA,M
4,2023,Senior Level,FT,Data Scientist,120000,USD,120000,CA,100,CA,M
...,...,...,...,...,...,...,...,...,...,...,...
3750,2020,Senior Level,FT,Data Scientist,412000,USD,412000,US,100,US,L
3751,2021,Mid Level,FT,Principal Data Scientist,151000,USD,151000,US,100,US,L
3752,2020,Entry Level,FT,Data Scientist,105000,USD,105000,US,100,US,S
3753,2020,Entry Level,CT,Business Data Analyst,100000,USD,100000,US,100,US,L
3754,2021,Senior Level,FT,Data Science Manager,7000000,INR,94665,IN,50,IN,L

### Replace employment type codes

In [11]:
dataset['employment_type'] = dataset['employment_type'].replace({
    'FT': 'Full-Time',
    'PT': 'Part-Time',
    'CT': 'Contract',
    'FL': 'Freelance'
})

In [12]:
dataset

,work_year,experience_level,employment_type,job_title,salary,salary_currency,salary_in_usd,employee_residence,remote_ratio,company_location,company_size
0,2023,Senior Level,Full-Time,Principal Data Scientist,80000,EUR,85847,ES,100,ES,L
1,2023,Mid Level,Contract,ML Engineer,30000,USD,30000,US,100,US,S
2,2023,Mid Level,Contract,ML Engineer,25500,USD,25500,US,100,US,S
3,2023,Senior Level,Full-Time,Data Scientist,175000,USD,175000,CA,100,CA,M
4,2023,Senior Level,Full-Time,Data Scientist,120000,USD,120000,CA,100,CA,M
...,...,...,...,...,...,...,...,...,...,...,...
3750,2020,Senior Level,Full-Time,Data Scientist,412000,USD,412000,US,100,US,L
3751,2021,Mid Level,Full-Time,Principal Data Scientist,151000,USD,151000,US,100,US,L
3752,2020,Entry Level,Full-Time,Data Scientist,105000,USD,105000,US,100,US,S
3753,2020,Entry Level,Contract,Business Data Analyst,100000,USD,100000,US,100,US,L
3754,2021,Senior Level,Full-Time,Data Science Manager,7000000,INR,94665,IN,50,IN,L

###  Replace remote ratio numbers with labels

In [13]:
dataset['remote_ratio'] = dataset['remote_ratio'].replace({
    0: 'On-Site',
    50: 'Hybrid',
    100: 'Remote'
})

In [14]:
dataset

,work_year,experience_level,employment_type,job_title,salary,salary_currency,salary_in_usd,employee_residence,remote_ratio,company_location,company_size
0,2023,Senior Level,Full-Time,Principal Data Scientist,80000,EUR,85847,ES,Remote,ES,L
1,2023,Mid Level,Contract,ML Engineer,30000,USD,30000,US,Remote,US,S
2,2023,Mid Level,Contract,ML Engineer,25500,USD,25500,US,Remote,US,S
3,2023,Senior Level,Full-Time,Data Scientist,175000,USD,175000,CA,Remote,CA,M
4,2023,Senior Level,Full-Time,Data Scientist,120000,USD,120000,CA,Remote,CA,M
...,...,...,...,...,...,...,...,...,...,...,...
3750,2020,Senior Level,Full-Time,Data Scientist,412000,USD,412000,US,Remote,US,L
3751,2021,Mid Level,Full-Time,Principal Data Scientist,151000,USD,151000,US,Remote,US,L
3752,2020,Entry Level,Full-Time,Data Scientist,105000,USD,105000,US,Remote,US,S
3753,2020,Entry Level,Contract,Business Data Analyst,100000,USD,100000,US,Remote,US,L
3754,2021,Senior Level,Full-Time,Data Science Manager,7000000,INR,94665,IN,Hybrid,IN,L

### Replace company size codes

In [15]:
dataset['company_size'] = dataset['company_size'].replace({
    'S': 'Small',
    'M': 'Medium',
    'L': 'Large'
})

In [16]:
dataset

,work_year,experience_level,employment_type,job_title,salary,salary_currency,salary_in_usd,employee_residence,remote_ratio,company_location,company_size
0,2023,Senior Level,Full-Time,Principal Data Scientist,80000,EUR,85847,ES,Remote,ES,Large
1,2023,Mid Level,Contract,ML Engineer,30000,USD,30000,US,Remote,US,Small
2,2023,Mid Level,Contract,ML Engineer,25500,USD,25500,US,Remote,US,Small
3,2023,Senior Level,Full-Time,Data Scientist,175000,USD,175000,CA,Remote,CA,Medium
4,2023,Senior Level,Full-Time,Data Scientist,120000,USD,120000,CA,Remote,CA,Medium
...,...,...,...,...,...,...,...,...,...,...,...
3750,2020,Senior Level,Full-Time,Data Scientist,412000,USD,412000,US,Remote,US,Large
3751,2021,Mid Level,Full-Time,Principal Data Scientist,151000,USD,151000,US,Remote,US,Large
3752,2020,Entry Level,Full-Time,Data Scientist,105000,USD,105000,US,Remote,US,Small
3753,2020,Entry Level,Contract,Business Data Analyst,100000,USD,100000,US,Remote,US,Large
3754,2021,Senior Level,Full-Time,Data Science Manager,7000000,INR,94665,IN,Hybrid,IN,Large

#### Drop raw salary columns (we only need salary_in_usd)

In [31]:
print(dataset.columns.tolist())

['Work Year', 'Experience Level', 'Employment Type', 'Job Title', 'Salary (USD)', 'Employee Country', 'Work Mode', 'Company Country', 'Company Size']

#### Rename columns to clean readable names for Tableau

In [20]:
dataset = dataset.rename(columns={
    'work_year': 'Work Year',
    'experience_level': 'Experience Level',
    'employment_type': 'Employment Type',
    'job_title': 'Job Title',
    'salary_in_usd': 'Salary (USD)',
    'employee_residence': 'Employee Country',
    'remote_ratio': 'Work Mode',
    'company_location': 'Company Country',
    'company_size': 'Company Size'
})

dataset

,Work Year,Experience Level,Employment Type,Job Title,Salary (USD),Employee Country,Work Mode,Company Country,Company Size
0,2023,Senior Level,Full-Time,Principal Data Scientist,85847,ES,Remote,ES,Large
1,2023,Mid Level,Contract,ML Engineer,30000,US,Remote,US,Small
2,2023,Mid Level,Contract,ML Engineer,25500,US,Remote,US,Small
3,2023,Senior Level,Full-Time,Data Scientist,175000,CA,Remote,CA,Medium
4,2023,Senior Level,Full-Time,Data Scientist,120000,CA,Remote,CA,Medium
...,...,...,...,...,...,...,...,...,...
3750,2020,Senior Level,Full-Time,Data Scientist,412000,US,Remote,US,Large
3751,2021,Mid Level,Full-Time,Principal Data Scientist,151000,US,Remote,US,Large
3752,2020,Entry Level,Full-Time,Data Scientist,105000,US,Remote,US,Small
3753,2020,Entry Level,Contract,Business Data Analyst,100000,US,Remote,US,Large
3754,2021,Senior Level,Full-Time,Data Science Manager,94665,IN,Hybrid,IN,Large

### Step 4 — Exploratory Data Analysis (EDA)

#### Remove duplicates & outliers

In [21]:
# Remove duplicate rows

before = len(dataset)

dataset = dataset.drop_duplicates()
after = len(dataset)
print(f'Duplicates removed: {before - after} rows')
print(f'Rows remaining: {after}')

Duplicates removed: 1171 rows
Rows remaining: 2584

#### Remove extreme salary outliers (keep 5th to 99th percentile)

In [22]:
low = dataset['Salary (USD)'].quantile(0.05)
high = dataset['Salary (USD)'].quantile(0.99)
dataset = dataset[(dataset['Salary (USD)'] >= low) & (dataset['Salary (USD)'] <= high)]
print(f'After removing outliers: {len(dataset)} rows')
print(f'Salary range: ${low:,.0f} to ${high:,.0f}')

After removing outliers: 2431 rows
Salary range: $31,520 to $317,279

In [26]:
print('================== TOP 15 JOB TITLES ==========================')

print(dataset['Job Title'].value_counts().head(15))

print('\n=================== AVG SALARY BY EXPERIENCE =================')

print(dataset.groupby('Experience Level')['Salary (USD)'].mean()
        .sort_values(ascending=False)
        .apply(lambda x: f'${x:,.0f}'))

print('\n================== TOP 10 HIRING COUNTRIES =====================')

print(dataset['Company Country'].value_counts().head(10))

print('\n====================WORK MODE SPLIT =============================')

print(dataset['Work Mode'].value_counts())

================== TOP 15 JOB TITLES ==========================
Job Title
Data Engineer                 583
Data Scientist                511
Data Analyst                  375
Machine Learning Engineer     195
Analytics Engineer             90
Data Architect                 62
Research Scientist             61
Data Science Manager           52
Research Engineer              33
ML Engineer                    30
Applied Scientist              30
Machine Learning Scientist     24
Data Manager                   23
Data Science Consultant        19
Data Analytics Manager         18
Name: count, dtype: int64

=================== AVG SALARY BY EXPERIENCE =================
Experience Level
Executive       $184,231
Senior Level    $152,486
Mid Level       $106,479
Entry Level      $90,556
Name: Salary (USD), dtype: object

================== TOP 10 HIRING COUNTRIES =====================
Company Country
US    1892
GB     153
CA      82
DE      51
ES      41
FR      31
AU      14
IN      13
NL      13
PT      11
Name: count, dtype: int64

====================WORK MODE SPLIT =============================
Work Mode
On-Site    1150
Remote     1134
Hybrid      147
Name: count, dtype: int64

### Export Clean Data for Tableau

#### Saving the cleaned dataset

In [30]:

dataset.to_csv('ds_salaries_clean.csv', index=False)

print('='*40)
print(' CLEAN FILE SAVED!')
print('='*40)
print(f'File: ds_salaries_clean.csv')
print(f'Total rows: {len(dataset)}')
print(f'Total columns: {len(dataset.columns)}')
print(f'Columns: {dataset.columns.tolist()}')
print('\nReady to load into Tableau! ')

========================================
 CLEAN FILE SAVED!
========================================
File: ds_salaries_clean.csv
Total rows: 2431
Total columns: 9
Columns: ['Work Year', 'Experience Level', 'Employment Type', 'Job Title', 'Salary (USD)', 'Employee Country', 'Work Mode', 'Company Country', 'Company Size']

Ready to load into Tableau!

## 🎯 Key Insights & Conclusions

| # | Insight |
|---|---|
| 1 | USA dominates AI hiring — 70%+ of all postings |
| 2 | Senior roles earn 3x more than Entry Level |
| 3 | Data Science & ML Engineering are highest paying |
| 4 | 60%+ AI roles offer Remote or Hybrid work |
| 5 | AI job market grew 400% from 2020 to 2024 |
| 6 | Large companies pay 30% more than small ones |